title: Alitudo S d.o.o.
logo: /assets/img/Alitudo2logo.png
# url: https://www.alitudos.hr/
description: Advisory services in food products development and food safety
show_downloads: false
google_analytics: UA-240159649-1
github:
  is_project_page: false
  is_user_page: false
theme: jekyll-theme-minimal
plugins:
    - jekyll-seo-tag
