title: Alitudo S d.o.o.
logo: /assets/img/logo-alitudo.png
description: Advisory services in food products development and food safety
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
