title: Alitudo S d.o.o.
logo: /assets/img/Alitudo2logo.png
description: Advisory services in food products development and food safety
show_downloads: false
google_analytics: UA-240159649-1
github:
  is_project_page: false
github:
  is_user_page: false
theme: jekyll-theme-minimal
